### ISSUE TITLE
 Could not connect to discovered hub: got tired of waiting - Causing Homebridge Loop Restart

### ISSUE THREAD

**Issue by donavanbecker** [thenewwazoo/homebridge-lutron-caseta-leap#10]
**Describe The Bug:**

When using internet and homebridge restart... this can happen.

**To Reproduce:**

disconnect internet and network, restart homebridge.

**Expected behavior:**

catch error and just log, not cause homebridge to restart.

**Logs:**

```
[Lutron] Could not connect to discovered hub: got tired of waiting
Error: Timed out waiting for bridge to appear
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lutron-caseta-leap/src/BridgeManager.ts:23:31)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
[1/20/2022, 12:01:21 PM] [Lutron] Child bridge process ended
```

**Plugin Config:**

```json

```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**:  v1.4.0-beta.7
* **Node.js Version**:  v16.13.2
* **NPM Version**:  v8.3.1
* **Operating System**: macOS

**Comment by thenewwazoo** [comment]
Thanks for the report. If you discover anything more than what we discussed on Discord, please let me know. I'm continuing to look into this.

**Comment by thenewwazoo** [comment]
This still has me totally flummoxed. I've stuck trace logging in the code, and my hunch is right: the PicoRemote constructor is awaiting the bridge, and throwing when it times out, but for some reason the try-catch block around the `new` call just... doesn't work? I have nfi.

**Comment by donavanbecker** [comment]
Not a huge deal as long as your plugin is put in a child bridge so it's not restarting all of homebridge.

**Comment by thenewwazoo** [comment]
Okay, so I get this now. I'm using an IIFE inside the constructor to enable awaiting the bridge. This detaches the constructor context from the timeout that happens. In short: trying to do complicated things in the constructor is a code smell anyway, and I should probably refactor this to not be fake-OOP with objects I construct and then throw away.

Fixing this is going to require a refactor to clean up the above. It bugs the shit out of me that the plugin crashes, though. :)

**Comment by khowell20454** [comment]
Same issue here, just installed this plugin today with all of the credentials and getting the same response in Homebridge. Tried switching Homebridge to insecure as mentioned in another issue but did not fix.

> [Lutron] Could not connect to discovered hub: got tired of waiting
Error: Timed out waiting for bridge to appear
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lutron-caseta-leap/src/BridgeManager.ts:23:31)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
[1/20/2022, 12:01:21 PM] [Lutron] Child bridge process ended

**Comment by thenewwazoo** [comment]
Can you please enable debug logging and attach a complete log?

**Comment by donavanbecker** [comment]
@khowell20454 , I got this when there was no internet going to homebridge. I would guess yours is different. You may want to open another issue and attach logs as @thenewwazoo has requested.

**Comment by HulacSt** [comment]
I was having a similar issue on 2.2.1 with homebridge 1.4 running on a raspberry pi 0w. I switched to a raspberry pi 3b on LAN and now it's working just fine. Not sure if it's the LAN or increased computing power that helped but I can play with it tomorrow.

**Comment by readybeginn** [comment]
I'm having a similar issue. Rpi3B running homebridge 1.4.0. When opening settings for initial configuration, it times out trying to load them.

<img width="932" alt="image" src="https://user-images.githubusercontent.com/64487254/159489799-674c5b61-9066-4a7e-8b50-a6fa7f6682db.png">

**Comment by BarnesGH** [comment]
This is what it does when using Hoobs as well (which I know is not currently supported unfortunately)
