### ISSUE TITLE
Step Dimmer Control

### ISSUE THREAD

**Issue by ssuro** [thenewwazoo/homebridge-lutron-caseta-leap#101]
**Is your feature request related to a problem? Please describe:**
The Pico 5 button remote doesn't seem to be able to function as a dimmer controller with this plugin.  It appears I can only set a button press to a specific illumination intensity.    It would be great to see a long press stepping function added to the plugin so that the pico remote can be made to function as it does with native lutron dimmers.  

**Describe the solution you'd like:**
I'd Like to see a Stepping function added to the plugin so that while pressing an holding a button the function will slowly step up or step down the percent illumination scale. 

the main goal would be to simulate the operation of a standard Lutron Caseta wall dimmer including the press and hold functionality for the raise/lower buttons. It would be amazing if it could allow for the control over the on/off transition times, brightness step percentage and the transition time.

**Comment by thenewwazoo** [comment]
I totally agree, but unfortunately this is a gap in HomeKit. Basically, buttons are stateless in HomeKit, meaning they can trigger events ("pressed", "double-pressed", "long-pressed") that happen at points in time, but they don't carry state like switches do ("on" or "off", or "pressed" or "released"). HomeKit further doesn't have a notion of "do a thing _until_ another thing" or "do _more_ of a thing". That means that buttons are limited to triggering the kinds of actions that are idempotent, don't have a start or an end, and don't have any sense of what the "past" was.

That means, basically, scenes, which let you "set the light to on" but not "raise the light by 5% from its prior value".

Such a feature could be wired up outside of HomeKit (and, thus, outside of this plugin), but you'd need to look into things like HomeAssistant or NodeRED or the like.
