### ISSUE TITLE
Caseta Bridge through this plugin only

### ISSUE THREAD

**Issue by keness521** [thenewwazoo/homebridge-lutron-caseta-leap#102]
Hello! I’m very excited to be about to try out your plug-in. I had a question about whether I can use your plug-in to control Pico remotes that are attached to a Caseta bridge, even if that bridge has not itself been added to HomeKit?

To explain, I plan on using a significant number of Pico remotes in my home to control non-Lutron shades, and also window openers. So I need to map the buttons in a way that I wouldn’t be able to do in the Lutron app, so I’ll be using your plug-in.

I don’t, however, plan to use ANY Lutron devices other than the Pico remotes, so I was just going to get a Bridge (arrives tomorrow) and use the Lutron app to connect the Picos to it so that your plug-in can see them, but NOT actually add the Caseta bridge itself to HomeKit. That way, I don’t have to worry about any duplication in HomeKit or an unnecessary bridge or anything like that.

Is this a viable set up, or does it only work if I also add the Caseta bridge to HomeKit?

Additionally, in case it matters, I’m planning on probably around 30 or 40 Picos. Actually, probably more like 40 or 50. Hmm… Now that I really think about it, based on the number of windows, it might be more like over 60. Does that number of remotes sound like it would be a problem? If so, can I get around it by having multiple bridges, and split the remotes between them?

One other question, I was reading through the various issues, and I wasn’t clear if the problem with the Pico remotes key associations disappearing had been fully squashed? Considering the number I’m planning, if I lost all my associated actions, I would probably cry. Hah! I do have the Controller app, and keep back ups, so I think I could restore them if it did happen, but was wondering if that had been fixed?

Thanks so much for your work on this plug-in! I’ve been looking for quite a long time for an ideal way to control my Zigbee roller shades, and Zigbee window openers in a nice tidy way, and the Pico remotes were about the only thing I came up with.

**Comment by act9999** [comment]
I’m currently running a similar setup:

-Caseta bridge (added to Homekit)
-40+ Picos (and growing)
-No other Lutron devices

Haven’t experienced any duplicates or other issues from adding the bridge to homekit. One hiccup is that the homekit rooms will synced into caseta hub, but all of the picos will be added to the room where the bridge is located in homekit, but you can change them in homekit after.

PS - If you’re looking for the PJ2-3BRL-GWH-L01 picos, I have about 25 extra that need a new home.

**Comment by thenewwazoo** [comment]
The plugin uses LEAP to communicate with the Smart Bridge 2, which has no dependency upon HomeKit at all. So, basically, the answer to your first question is: yes, it'll work fine. No need to set up HomeKit in the Lutron application.

I am currently working on a refactor of the Pico code that will prevent associations getting lost when network issues happen. That's probably still a few weeks out from being ready for wide adoption, but I can ping you in this thread if you want to be an early tester. For now, making sure that you're using a child bridge, that Homebridge is running on reasonably powerful hardware, and that your network is absolutely bombproof should be enough insurance.

**Comment by keness521** [comment]
Sounds great, and I'll be keeping an eye on this repository anyway, so I should see if you start commenting about a new beta with the refactored code and I'll pop back in! Definitely happy to help test it out. And I can probably "simulate" power and or network failures to test out the robustness of the new code, though I'm afraid I'm not very technical on the software side of things.

Great news on the bridge not needing to be in HomeKit. I prefer to keep HomeKit as "clean" as possible since it is so finicky.

No problem on Child Bridge, I use that for everything. In fact, I don't even have the main Homebridge bridge added to HomeKit, because nothing is "in" it. I'm in a Pi4, so that should be good on that front.

As for the network being bulletproof... Well... I do have a very robust network, but... Real world. haha If it were bulletproof we would never have ANY network problems. :)

I sent a support question to the Controller app developer to see if the backups it creates can restore the associations to the buttons. I suspect there is no problem with SCENES attached to the buttons, but if you use Apple Actions, which Controller can't edit or manipulate, I don't know if it can back them up, either. Will report back.

Thanks!
