### ISSUE TITLE
How to hide Picos set up in Lutron App

### ISSUE THREAD

**Issue by sptv1** [thenewwazoo/homebridge-lutron-caseta-leap#103]
**Describe Your Problem:**
As the heading says, how do I hide existing Picos that are already set up in the Lutron app? I don't understand the information presented in GitHub. I have 4 picos. Three are already associated. One is new, which is why I am using the plugin on Hoobs. I only want the one new one to add to HomeKit, not the other three that are already there.

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by thenewwazoo** [comment]
Sorry, this plugin can be used with HOOBS but I don't use HOOBS myself and so can't support it. In the Homebridge UI there is a toggle to hide already-associated Picos. That's the setting you want. In the config JSON object, it's `filterPico`.
