### ISSUE TITLE
Plug-in Keeps Restarting

### ISSUE THREAD

**Issue by mirinjesse** [thenewwazoo/homebridge-lutron-caseta-leap#106]
Problem:

Trying to use the plugin with my RA 3 processor to get picos in homekit setup for the first time. My Pico works fine with Lutron app, but is not being pulled into the homebridge plugin. I have successfully been able to find and connect to my RA 3 processor, but plug-in looks like it’s having some issues and keeps restarting. In my dashboard the status light keeps going yellow, green, red and when I tried to add it to homekit I get a failed indicator.

I am not sure if it’s a bug or I missed a step in the setup guide or both.

**Comment by thenewwazoo** [comment]
Unfortunately, this plugin doesn't support RA3 processors, mostly because I don't have one to test with. Sorry. :(
