### ISSUE TITLE
Expose Light Switch As Stateless Buttons

### ISSUE THREAD

**Issue by simplytoast1** [thenewwazoo/homebridge-lutron-caseta-leap#108]
**Is your feature request related to a problem? Please describe:**
I wish that even though light switches are enabled in HomeKit natively via the Caseta Hub, I would like the ability to drive more automations off the switches as if they were picos.

**Describe the solution you'd like:**

Currently, as a HomeKit automation if I enter a room with a Caseta enabled switch I set a trigger to "if this device turns on, then do this" action. I would love the ability to expose HomeKit enabled Caseta switches as stateless buttons.  IE: Power on is a button and Power off is a button so I can drive an automation directly off a button press. 

**Describe alternatives you've considered:**
The only alternative is to setup an automation based on the power state of a device.

**Additional context:**
Is this a good ask, no but i love how instant off the Picos I can drive a automation or scene and have been spoiled by that the waiting for the delay of a light turning on and triggering another action.

**Comment by thenewwazoo** [comment]
Sadly, this isn't possible, thought it is a [long-standing request](https://github.com/thenewwazoo/homebridge-lutron-caseta-leap/issues/5).
