### ISSUE TITLE
Memory Leak associated with Lutron plug-in

### ISSUE THREAD

**Issue by dxa13** [thenewwazoo/homebridge-lutron-caseta-leap#109]
Hi,

I could use some help for a memory leak that surfaced 2 weeks ago.  I am running on a Raspberry PI, and have been happily using your plug-in since its inception, running it as a child bridge, on a house with 16 pico remotes, out of which 2 are controlled by both Lutron and the plug-in, and 4 are exclusively controlled by the plug-in. Hence I only care about 6 of them for the plug-in.

It takes ~6-12hrs for the memory to slowly creep up to the point where my Pi runs out of memory. In the process of growing in memory utilization, CPU is also pegged at 100% for the child bridge, which did not used to be the case before the problem started.  That high CPU also causes the Pico remote actions (in the plug-in) to have a 2-5 second delay, which is very annoying, and even more (10-15 sec, if at all) once memory gets filled. I know the memory leak is caused by the lutron plug-in because if I stop or restart just the lutron child bridge then memory (and cpu) goes back down, and all starts working again for a few hours.

When starting homebridge, I get these messages:

[5/17/2023, 8:54:34 AM] [Lutron] Got MaxListenersExceededWarning process warning: Possible EventEmitter memory leak detected. 76 disconnected listeners added to [SmartBridge]. Use emitter.setMaxListeners() to increase limit:
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 76 disconnected listeners added to [SmartBridge]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:587:17)
    at SmartBridge.addListener (node:events:605:10)
    at PicoRemote.initialize (/var/lib/homebridge/node_modules/homebridge-lutron-caseta-leap/src/PicoRemote.ts:229:25)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at LutronCasetaLeap.processDevice (/var/lib/homebridge/node_modules/homebridge-lutron-caseta-leap/src/platform.ts:230:24)
    at async Promise.allSettled (index 49)
    at /var/lib/homebridge/node_modules/homebridge-lutron-caseta-leap/src/platform.ts:197:61

Things that have changed recently:
- Node was updated as part of the latest OS updates.
- Homebridge got updated to 1.6.1
- Added a new Pico Remote 3 days ago.
- I have changed the actions of the buttons in two of the picos used with the plug-in, adding more actions (long press, double press).  

I tried:
- restarting homebridge and/or the raspberry pi -> no effect
- downgrading node -> no effect
- downgrading home bridge to 1.6.0 -> no effect
- downgrading the lutron plug-in to 2.4.3 -> I could swear it fixed the problem for 4 days, then I added a new pico 3 days ago and now the problem is back.
- Enabled "Exclude Pico remotes that are associated in the Lutron app", which is not ideal for me given I have 2 remotes I linked to both Lutron and the plug-in.  -> Above warning goes away, but no effect on high CPU and memory leak.

I am happy to provide more info/logs if you tell me how... Any help would be appreciated!  I am starting to suspect that maybe the trigger for all of this was adding more actions to the pico remotes. Would that make sense?

Regards,
Diego

**Comment by thenewwazoo** [comment]
Hi @dxa13, I'm sorry to hear you're having problems. One other user reported a similar problem in #20, but we never really got to the bottom of it. Fortunately, I built a tool to trigger heap dumps. Please read through that thread and attach a heap dump to this one, and I'll try to find time to take a look.

**Comment by thenewwazoo** [comment]
Do you have the lutron plugin configured to [run in a child process](https://github.com/thenewwazoo/homebridge-lutron-caseta-leap#something-weird-is-happening--the-plugin-is-running-slowly--devices-arent-appearing)?

**Comment by dxa13** [comment]
Hi @thenewwazoo, thanks for your wiliness to help!  I am running the plug-in as a child bridge/process, always have, which means I have the ability to reboot just that one bridge to make the problem (temporarily) go away.  It seems the memory leak went away for a day, raspberry pi's free memory held steady at 0.4GB and <30% overall cpu usage, but then as soon as pressed one of the pico remote button (tied to the plugin) a few minutes ago it all went to hell and memory filled in <60min.  

The first two heap dumps are from right before memory was about to reach 100% usage.  The third and last dump is right after I restarted Homebridge (on its entirety) after also enabling the debug env variable in the UI using leap.*  

After the reboot, free memory went down quite rapidly to 0.36GB, and I can tell there is something wrong (i.e. the memory leak) because the CPU has been at >60% (which means 90-99% for the Lutron bridge) constantly.  As I type this, memory is now down to 0.35GB....

I'll upload a new heap dump after letting it run to its near death again.

[lutron.1684802060227.after23hr.20230522_20_34.heapsnapshot.zip](https://github.com/thenewwazoo/homebridge-lutron-caseta-leap/files/11538158/lutron.1684802060227.after23hr.20230522_20_34.heapsnapshot.zip)
[lutron.1684802060227.after23hr.20230522_20_37.heapsnapshot.zip](https://github.com/thenewwazoo/homebridge-lutron-caseta-leap/files/11538159/lutron.1684802060227.after23hr.20230522_20_37.heapsnapshot.zip)
[lutron.1684802735487.after1min.20230522_20_46.heapsnapshot.zip](https://github.com/thenewwazoo/homebridge-lutron-caseta-leap/files/11538160/lutron.1684802735487.after1min.20230522_20_46.heapsnapshot.zip)

**Comment by dxa13** [comment]
Here is another heap dump 2hrs after the last one.  Free memory is down to 0.3GB, CPU still pegged by the plugin at >90%.  Since this last dump command, I am guessing as a result of it, and as I type this, free memory has now quickly dropped to 0.19GB and still going, so I may need to reboot the child bridge soon.

[lutron.1684810848710.after2hr.20230522_23_02.heapsnapshot.zip](https://github.com/thenewwazoo/homebridge-lutron-caseta-leap/files/11538882/lutron.1684810848710.after2hr.20230522_23_02.heapsnapshot.zip)

**Comment by dxa13** [comment]
Here is ending heap dump before rebooting the child bridge, 12hr runtime, 0.14GB free memory left, CPU still pegged by the Lutron plugin at >90%.

[lutron.1684844130015.after12hr.20230523_08_17.heapsnapshot.zip](https://github.com/thenewwazoo/homebridge-lutron-caseta-leap/files/11543739/lutron.1684844130015.after12hr.20230523_08_17.heapsnapshot.zip)

And Log:

[homebridge (1).log.zip](https://github.com/thenewwazoo/homebridge-lutron-caseta-leap/files/11543755/homebridge.1.log.zip)

**Comment by dxa13** [comment]
As an update, I removed all long press automations from all pico remotes, and so far after 26hrs the memory leak seems to be gone.  I won’t know for sure until probably a few more day's worth of runtime, but this seems to make sense given that the problem started when I added the long press actions a few weeks ago.

**Comment by thenewwazoo** [comment]
Oh fun. Chrome Dev Tools crashes when I load the larger heap dumps. I suspect it's more than my laptop (24 GB M2 MBAir) can handle.

Any chance you can restart, take a heap dump after the app settles, and then take one after some time has passed and memory consumption has increased but not yet eaten the whole RPi? Say, after some few hundred MB increase instead of a few GB? Maybe Chrome won't die with a smaller heap dump. 

Thank you for being willing to help me diagnose this!

**Comment by dxa13** [comment]
Here is another one after 2hr, memory has gone down 60MB in a period of 2hr, so it definitely still has a memory leak.
[lutron.1685368417918.after2hr.20020529_09_54.heapsnapshot.zip](https://github.com/thenewwazoo/homebridge-lutron-caseta-leap/files/11592259/lutron.1685368417918.after2hr.20020529_09_54.heapsnapshot.zip)

**Comment by thenewwazoo** [comment]
Based on the heap dumps themselves, the difference is 1618 kB. This is feeling like a repeat of #20. :(

**Comment by dxa13** [comment]
Just an update in an attempt to also document where am I at and what I have tried to isolate the issue. As a reminder, the plugin is running as a child bridge in homebridge.  Restarting the lutron child bridge brings the memory back down, but not necessarily the constantly high CPU utilization (anything above 25% is abnormal) as the main symptom the issue is happening, which means memory utilization will go back up within 6-12hrs and make my raspberry pi and therefore homebridge quite unresponsive/slow.

When starting child bridge I still get the following disturbing warning(s).  If you @thenewwazoo have an idea as to how to tackle this one, whether it relates or not to the issue, it would be appreciated. 

(node:16785) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 76 disconnected listeners added to [SmartBridge]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
[6/23/2023, 9:06:24 AM] [Lutron] Got MaxListenersExceededWarning process warning: Possible EventEmitter memory leak detected. 76 disconnected listeners added to [SmartBridge]. Use emitter.setMaxListeners() to increase limit:
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 76 disconnected listeners added to [SmartBridge]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:585:17)
    at SmartBridge.addListener (node:events:603:10)
    at PicoRemote.initialize (/var/lib/homebridge/node_modules/homebridge-lutron-caseta-leap/src/PicoRemote.ts:229:25)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at LutronCasetaLeap.processDevice (/var/lib/homebridge/node_modules/homebridge-lutron-caseta-leap/src/platform.ts:230:24)
    at async Promise.allSettled (index 49)
    at /var/lib/homebridge/node_modules/homebridge-lutron-caseta-leap/src/platform.ts:197:61

Isolating the issue:
- None of the suggestions and reconfiguration in [https://github.com/thenewwazoo/homebridge-lutron-caseta-leap/issues/20](url) and [https://github.com/nodejs/help/issues/1518](url) to change the memory allocator helped.
- Restarting the child bridge, homebridge, or the Raspberry Pi only temporarily solves the issue (i.e. for ~6-12hrs or so).
- Enabling or disabling "Exclude Pico remotes that are associated in the Lutron app" in the plug-in settings has no effect, though enabling this option does get rid of the above warning.
- Rebuilding a fresh image of Raspbian OS, with a fresh install of homebridge and then adding the lutron plugin (which took a lot of time), had no effect on the issue.  In other words, my Raspian or homebridge environment are not at fault.
- Allowing the Lutron hub to talk to the outside world or not (via my router) has no effect. Monitoring network traffic in/out of the Lutron hub shows no unusual activity.
- To reiterate, if I disable the lutron child bridge in homebridge, the problem does not occur.

My latest discovery though is that I can make the problem go away for ~2 days by simply rebooting my main Ubiquity router, AND then rebooting the lutron child bridge in homebridge.  That will, in addition to bringing the memory back down, cause the CPU utilization to drop to a steady 20-25%.  It lasts for about 2 days, then the problem shows it ugly face again after two days when CPU utilization does up to 50-60% and then memory utilization gradually climbs. Nothing will bring the CPU down at that point except rebooting my main router again.  I am of course baffled by this discovery, how can network activity have a direct effect on the lutron child bridge and only it? @thenewwazoo, is there a way to monitor (via log messages, or traces) what the lutron plugin is doing or seeing when CPU utilization is low (i.e. after I reboot my router) vs when it is high (i.e. after two days when the problem re-surfaces)?

**Comment by dxa13** [comment]
As another update, I have found the trigger to the problem with the Lutron plug-in which results in high cpu and the memory leak. I have a Mac running Home Assistant and every time home assistant is rebooted (I.e. as part of an update), it instantly triggers the problem with the raspberry PI running the Lutron plug-in (i.e. cpu shoots home from 25% to 60%+ and available memory starts to go down). Any ideas as to what HomeAssistant could be injecting into the network to make the Lutron plug-in (or associated npm/homebridge child process) go crazy? To make the problem go away after that, I simply need to reboot my small Ubiquiti network switch that feeds the Mac via Ethernet, or shut down HomeAssistant (the latter is not a good option), and finally reboot the Lutron child bridge in homebridge.  As long as I don’t reboot HomeAssistant, everything remains happy. I’ll keep investigating what in HomeAssistant could be making the Lutron plug-in very upset…

**Comment by thenewwazoo** [comment]
This is _wild_. I have _no idea_ what HA could be doing, but I'd _love_ to see a packet dump of the network traffic... uh, and a week to dedicate to the diagnosis. I suspect this is a bug somewhere in the guts of Homebridge. I'm going to close this up since there's nothing I can do from my side.
