### ISSUE TITLE
Ra3 Bridge connection - Crashes homebridge upon booting

### ISSUE THREAD

**Issue by NBerk2** [thenewwazoo/homebridge-lutron-caseta-leap#110]
**Describe The Bug:**
Plugin crashes upon reading RA3 "devices" properties

**To Reproduce:**
Connect Caseta leap plugin to RA3 Controller

**Expected behavior:**
Boot without crashing and inventory devices, as it does with Caseta and RA2 Select

**Logs:**

```
[5/24/2023, 5:09:46 AM] [Lutron] got request to add bridge 04e58ac4
TypeError: Cannot read properties of undefined (reading 'Devices')
    at SmartBridge.getDeviceInfo (/homebridge/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/SmartBridge.ts:135:53)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[5/24/2023, 5:09:46 AM] [Lutron] Child bridge process ended
```

**Plugin Config:**

```json
   {
            "name": "Lutron",
            "platform": "LutronCasetaLeap",
            "options": {
                "filterPico": false,
                "filterBlinds": false,
                "clickSpeedDouble": "default",
                "clickSpeedLong": "default"
            },
            "secrets": [
                {
                    "bridgeid": "04E58AC4",
                    "ca": "-----BEGIN CERTIFICATE-----
                         \n-----END CERTIFICATE-----\n",
                    "cert": "-----BEGIN CERTIFICATE-----
                                 n-----END CERTIFICATE-----\n",
                    "key": "-----BEGIN RSA PRIVATE KEY-----
                                  -----END RSA PRIVATE KEY-----\r\n"
                }
            ],
            "_bridge": {
                "username": "0E:99:2C:7C:FC:C1",
                "port": 55365
            }
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: <1.6.1 (latest)>
* **Node.js Version**: <Latest>
* **NPM Version**: <Latest>
* **Operating System**:

**Comment by thenewwazoo** [comment]
Hi @NBerk2 this crash is not a great one, and I'm sorry it's happening to you. I don't have a quick fix, but as a workaround, you can remove the secret entry for the RA3 processor, as it's not supported by this plugin. I've got plans (and a fair pile of code) to enable future support for non-Caseta devices, but it's not available yet.

**Comment by NBerk2** [comment]
All good, I realized post submission that bug, was a mistake and feature request was the more accurate submission but could not change it after the fact.

While contributing HW is not doable for me personally, if I can facilitate in any way I’d be happy to do so. Appreciate the work done thus far in your plugin.

Thank you for the follow up!

On May 24, 2023, at 10:28 PM, Brandon Matthews ***@***.***> wrote:

﻿

Hi @NBerk2<https://github.com/NBerk2> this crash is not a great one, and I'm sorry it's happening to you. I don't have a quick fix, but as a workaround, you can remove the secret entry for the RA3 processor, as it's not supported by this plugin. I've got plans (and a fair pile of code) to enable future support for non-Caseta devices, but it's not available yet.
