### ISSUE TITLE
 Bridge loses pico functionality if the hub is reconnected to the network

### ISSUE THREAD

**Issue by raulphillips** [thenewwazoo/homebridge-lutron-caseta-leap#111]
**Describe The Bug:**
If the Lutron hub is disconnected from the ethernet port and reconnected, the pico remote functionality disappears. When reconnecting the network cable to the hub, the log indicates [Lutron] Bridge XXXXXXXXX already known, ignoring.

**To Reproduce:**
It is only necessary to disconnect the hub from the network cable, wait a few minutes and reconnect. All functionality of pico remotes just disappears.

**Expected behavior:**
Homebridge should restore the connection with the Lutron hub, but it is ignoring it according to the log, the pico functionalities are not restored at any time, until Homebridge is rebooted.

**Logs:**
[19/06/2023, 23:10:09] [Lutron] Bridge XXXXXXX already known, ignoring.
[19/06/2023, 23:10:13] [Lutron] Bridge XXXXXXX already known, ignoring.
[19/06/2023, 23:14:05] [Lutron] Bridge XXXXXXX already known, ignoring.

**Plugin Config:**
{
            "name": "Lutron",
            "platform": "LutronCasetaLeap",
            "options": {
                "filterPico": false,
                "filterBlinds": false,
                "clickSpeedDouble": "default",
                "clickSpeedLong": "default"
            },
            "secrets": [
                {
                    "bridgeid": "XXXXXXXX",
                    "ca": "-----BEGIN CERTIFICATE----- XXXXXXXXXXXXX -----END CERTIFICATE-----\n",
                    "cert": "-----BEGIN CERTIFICATE----- XXXXXXXXXXXX -----END CERTIFICATE-----\n",
                    "key": "-----BEGIN RSA PRIVATE KEY---- XXXXXXXXXXXXXX-----END RSA PRIVATE KEY-----\r\n"
                }
            ]
        }

**Environment:**

* **Plugin Version**: v2.4.5-beta1
* **Homebridge Version**: v1.6.1
* **Node.js Version**: v14.17.1
* **NPM Version**: v7.17.0
* **Operating System**: Raspbian

**Comment by PaulDeas** [comment]
Yes!  This has been happening to me for a long time.  Thank you for figuring out how to reproduce it.  I tried unplugging my hub and got had the same situation.

**Comment by thenewwazoo** [comment]
This should be fixed in #123 :)

**Comment by thenewwazoo** [comment]
This should be fixed in #119! :)
