### ISSUE TITLE
Support for Wall/Plug-in Dimmers and Switches

### ISSUE THREAD

**Issue by bcbock** [thenewwazoo/homebridge-lutron-caseta-leap#112]
It would be useful to be able to assign additional functions triggered by wall switches. For example, I have a dimmer for the lights in the bathroom and a switch for the exhaust fan. I’d like a single press of the off switch of the light to turn on the fan for 5 minutes or shut it off after 5 minutes if it’s running. (I can do that now.) But I’d like to add a long press to leave it on for longer after a shower. I could add a Pico to do this, but I’d rather not add more controls to the bathroom.

**Comment by thenewwazoo** [comment]
Alas, button press events for non-Pico devices aren't exposed by Lutron. This is a common request that isn't available in the LEAP protocol.
