### ISSUE TITLE
Can't Connect to Smart Bridge

### ISSUE THREAD

**Issue by sptv1** [thenewwazoo/homebridge-lutron-caseta-leap#121]
**Describe Your Problem:**
I've been using your bridge for about a year and never had any problem with it until today. I changed my router (had been Linksys Velop, now switched to TP-Link XE75pro). I use Hoobs. The bridge could not log in with the new router. So I removed the bridge and tried to set it all up as new, and it gets stuck on the Searching for SmartBridges page. My Lutron smart bridge works fine, so that's not the problem. And my other Hoobs bridges are all fine too. Perhaps the problem relates to port forwarding? I don't know, but would sure like to get it working again!

Plugin is 2.4.5-beta1
Hoobs 16.20.2 (Homebridge 1.6.0)

Thank you.

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by thenewwazoo** [comment]
The plugin (and, indeed, all of Lutron's connectivity) relies on mDNS and DNS-SD, which requires that broadcast packets arrive. If you can see the Lutron device with your phone, but not on Homebridge, you'll need to figure out what's different between your Homebridge install and your phone (different WLAN? firewall rules?). Unfortunately, that's impossible to diagnose remotely, sorry.
