### ISSUE TITLE
Support for Pico paddle remotes: PJ2-P2B-GWH

### ISSUE THREAD

**Issue by Bleufarmer** [thenewwazoo/homebridge-lutron-caseta-leap#124]
Any plans to support the new Pico paddle remotes (PJ2-P2B-GWH)? I’m happy to send one over if given info on how to send!

**Comment by thenewwazoo** [comment]
I'd love to, but don't have plans to buy one. If you'd like to ship one to me, I'll gladly accept it. I predict it'll be exceptionally easy to add it. In fact, if you'd like to try, [this commit](https://github.com/thenewwazoo/homebridge-lutron-caseta-leap/commit/d8d26a9f10a472f33ddd7a692cf7b4d497a52278) is how I added support for 4-button remotes. If not, feel free to shoot me an email.

**Comment by thenewwazoo** [comment]
Released in v2.5.3! 🎉

**Comment by Bleufarmer** [comment]
Tested and working this morning, thanks!
