### ISSUE TITLE
Question: Support for 4 button -P01 Pico?

### ISSUE THREAD

**Issue by DonutEspresso** [thenewwazoo/homebridge-lutron-caseta-leap#128]
**Describe Your Problem:**
I'm interested in knowing if the current 4 button support in the plugin also supports the 4 button PJ2-4B-GWH-P01 'scene' Pico, which is natively supported by Caseta AFAICT. I'm interested in picking one up but would only want to use it through HK to control groups of both Lutron and non-Lutron devices. I've [gathered from #26](https://github.com/thenewwazoo/homebridge-lutron-caseta-leap/issues/26) that some form of the 4 buttons is currently supported by the plugin, and in [#33](https://github.com/thenewwazoo/homebridge-lutron-caseta-leap/issues/33) that the scene flavored 4 button `-P01` might also be supported. However, the readme does state only the `-L01` 4 button pico currently supported. I'm curious what the current state is? If the readme is outdated, I'm happy to file an update to it if there's a full list of supported picos for the plugin. 

If useful, it seem Lutron now have a KB article on [which Picos are fully supported within the Caseta system](https://support.lutron.com/us/en/product/casetawireless/article/product-selection/The-Pico-Remote).

Thanks, and appreciate your work on unlocking these capabilities for the community! 🙌 

**Logs:**
N/A

**Plugin Config:**
N/A

**Screenshots:**
N/A

**Environment:**
N/A

**Comment by thenewwazoo** [comment]
hmmm I'm honestly not sure. the way the Picos identify themselves to the hub is not necessarily congruent to how Lutron markets them, so it very well might Just Work. if you have one, can you give it a try and see how it appears in the startup log?

**Comment by DonutEspresso** [comment]
I don't have one at the moment, but was about to pull the trigger on it anyway to give it a try. Happy to provide logs and debug info if that's enough to get things going. Worst case - would you be up for me shipping the remote to you if you need it physically? I'm in the Bay Area so shipping would be pretty fast I think. 

Let me know if you'd prefer to keep this issue open, or I can open a new issue once I try it and get some logs. Thanks!

**Comment by thenewwazoo** [comment]
debug logs should be enough to add support if it's needed, plus maybe a bit of guesswork. let's keep this open so long as the feature request is "live" :)

**Comment by DonutEspresso** [comment]
Looks like the remote 'just works'! Was able to confirm single, double, and long press customization behavior. No setup or configuration necessary. Here's the device entry on startup:

```
    {
      Name: 'Keypad',
      DeviceType: 'Pico4ButtonScene',
      AssociatedArea: { href: '/area/2' },
      href: '/device/56',
      SerialNumber: 93292965,
      FullyQualifiedName: [ 'Family Room', 'Keypad' ],
      Parent: { href: '/project' },
      ModelNumber: 'PJ2-4B-GXX-P01',
      ButtonGroups: [ { href: '/buttongroup/16' } ],
      EngravingKit: 'LivingRoom',
      LinkNodes: [ { href: '/device/56/linknode/55' } ],
      DeviceRules: [ { href: '/devicerule/82' } ],
      AddressedState: 'Addressed',
      AssociatedLink: { href: '/link/1' }
    }
```

Anything else you'd like me to pull/capture from the logs to confirm?

**Comment by thenewwazoo** [comment]
Great news! I’d love a doc update PR if you could be convinced :)

**Comment by DonutEspresso** [comment]
PR opened. I'll close out this issue, thanks!
