### ISSUE TITLE
Devices not showing up in HomeKit

### ISSUE THREAD

**Issue by jondgrant** [thenewwazoo/homebridge-lutron-caseta-leap#132]
I'm having trouble with the pico devices showing up in my HomeKit.  The bridge exists in HomeKit and the number of accessories goes up by 1 each time I add a pico, but it's invisible on the accessory list and not showing up in any of the HomeKit rooms.

I successfully installed the plugin, associated my 2 Lutron bridges, and can see newly paired picos in my list of accessories within Homebridge.  But the devices are not pushing over somehow.  I am running this with the "exclude already associated picos" box checked.

I've tried running as a child bridge, pairing only one Lutron bridge, clearing the cached devices, restarting multiple time, to no avail.

**Comment by chrisbellco** [comment]
Just a quick "Me Too" here.

**Comment by jondgrant** [comment]
So I figured it out, for some reason the devices were coming over to my home kit with the setting “add to Home view” unchecked. It wasn’t until I opened up the “Default” room where they were assigned that I could see them. And then turned on the “add to Home view” button for each device.

**Comment by chrisbellco** [comment]
@jondgrant - Me too again, but only because of your follow-up post!  Thank you!

**Comment by thenewwazoo** [comment]
Glad it’s all resolved :)
