### ISSUE TITLE
Just a question before a purchase... or maybe more.

### ISSUE THREAD

**Issue by MoTechnicalities** [thenewwazoo/homebridge-lutron-caseta-leap#133]
**Describe Your Problem:**

**Logs:**

```
N/A
```

**Plugin Config:**

```
Regarding the new Pico Paddles... Does the plugin support double and long press for this remote as well?

Regarding the Regular wired Lutron CLARO switch... Do the ON & OFF buttons send a signal to the Lutron Bridge that the plugin can intercept??? to for example, allow a double or long press of that type of switch to be used by the plugin to activate a HomeKit scene?
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by thenewwazoo** [comment]
Feel free to email as well if you don’t want to open issues to ask questions! The paddle picos should Just Work, yep. No idea about the wired switches. Are they a Caseta thing? I’d expect them not to work, though.

**Comment by MoTechnicalities** [comment]
The Lutron Caseta Claro switches are precisely what I am talking about.
They are a paddle style that sits dead center until pressed UP for On or DOWN for Off.
HomeKit shows them On if you turn them on, but, what I am wondering is, if the switch is already On will it still send a signal to the Bridge that the plugin can use (same as the Pico paddles do) if the UP paddle on the switch again. Because, if so then that could open up button automation options for these Caseta switches as well. I have a couple of the Claro switches but have no way of knowing if they send anything to the Bridge when double or long-pressed. Thanks if you are willing to look into it or let me know what I can do.

This one --> https://electricalparts.com/cdn/shop/products/Image_03b93860-ccda-4252-ad0a-200b3e7ed8bf.jpg?v=1663340334

**Comment by MoTechnicalities** [comment]
So sorry I've been saying "CLARO", but I've been meaning "DIVA"... Got them mixed up there. The DIVA are the On/Off.

**Comment by thenewwazoo** [comment]
In every case I've seen so far, wired devices do not emit events, and don't have buttongroups that can be used for event subscription.
