### ISSUE TITLE
Lutron 4 Button LS21

### ISSUE THREAD

**Issue by PicoHelp** [thenewwazoo/homebridge-lutron-caseta-leap#137]
hi there. Firstly thank you for all those who support this plugin! Unknowingly I purchased the LS21 (4 button, 2 zone 1 light and one shade). Currently unsupported. Any thoughts on how I can use this in HomeKit. 

Thanks in advance. 

**Is your feature request related to a problem? Please describe:**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by s-gig** [comment]
I wanted an LS21 too, and bought one after seeing this issue with the intention of hopefully building in support myself and making a PR.

So I was very happy when I noticed it just popped up in HK anyway. I've tested out all four buttons and it works perfectly as is, the same as all my other Picos.

**Comment by thenewwazoo** [comment]
Fantastic, thank you for the report!
