### ISSUE TITLE
Infinite spinning gear  

### ISSUE THREAD

**Issue by GaintPumpkinz** [thenewwazoo/homebridge-lutron-caseta-leap#145]
**Describe Your Problem:**
 when i get inti the settings it just has a gear spinning i assume that means its looking for my lutron bridge and cant find it but im not sure what to do

**Logs:**
[2023-12-30, 3:31:58 p.m.] [Homebridge UI] [homebridge-lutron-caseta-leap] Incoming Request: /search
```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

![spinning gear](https://github.com/thenewwazoo/homebridge-lutron-caseta-leap/assets/121405843/258dc996-e35f-4c09-b674-3fbc1ce36c91)

**Environment:**

* **Plugin Version v2.5.3**:
* **Homebridge Version**:  v1.7.0
* **Node.js Version**:  v20.9.0
* **NPM Version**:  im too dumb to know 
* **Operating System**:  Microsoft Windows 10 Pro (10.0.19045)

**Comment by QandnotU** [comment]
I'm running into the same issue.

Environment:

Plugin Version v2.5.3:
Homebridge Version: v1.7.0
Node.js Version: v20.11.1
NPM Version: 10.2.4
Operating System: macOS Monterey

**Comment by GaintPumpkinz** [comment]
> I'm running into the same issue.
> 
> Environment:
> 
> Plugin Version v2.5.3: Homebridge Version: v1.7.0 Node.js Version: v20.11.1 NPM Version: 10.2.4 Operating System: macOS Monterey

I ended up getting it to work by making a VM running on linux and setting up a 2nd instance of homebridge on there the pluggin seems to work properly for me

**Comment by thenewwazoo** [comment]
Glad you got it to work. This is an indication that mDNS isn't working correctly, but the reasons for that are many, and impossible to diagnose at a distance.

**Comment by arjunmehta** [comment]
@thenewwazoo 

I'm currently experiencing this issue. No matter what I've tried I can't seem to get the Homebridge plugin to "find" the Lutron hub though I know it's IP.

I have Avahi set up on my router, and this was working fine when my Homebridge was running on a Raspberry Pi. I moved Homebridge over to a Proxmox LXC running Debian and since then this plugin can't find the Lutron hub. I'm hoping that it's something to do with my config but I wonder if mDNS works differently in Debian than Raspian.

If I manually try running `avahi-browse -r -a` I get the following entries:
```bash
...
+   eth0 IPv4 LAP Service                                   _lap._tcp            local
+   eth0 IPv4 Lutron Status                                 _lutron._tcp         local
+   eth0 IPv4 LEAP Service                                  _leap._tcp           local
...

=   eth0 IPv4 LAP Service                                   _lap._tcp            local
   hostname = [Lutron-XXXXXXXX.local]
   address = [192.168.2.133]
   port = [8083]
   txt = []
=   eth0 IPv4 Lutron Status                                 _lutron._tcp         local
   hostname = [Lutron-XXXXXXXX.local]
   address = [192.168.2.133]
   port = [22]
   txt = ["SYSTYPE=SmartBridge" "ST_STATUS=good" "NW_STATUS=InternetWorking" "FW_STATUS=1:NoUpdate" "DEVCLASS=08040100" "CODEVER=08.15.16f000" "MACADDR=XX:XX:XX:XX:XX:XX"]
=   eth0 IPv4 LEAP Service                                  _leap._tcp           local
   hostname = [Lutron-XXXXXXX.local]
   address = [192.168.2.133]
   port = [8081]
   txt = []
```

I think a useful workaround would be to just have a manual input for the IP for the hub.

**Comment by arjunmehta** [comment]
I saw another post and just restarted my hub and it works now! Can't believe I didn't try that first.
