### ISSUE TITLE
Cannot discover Smart Hub 2

### ISSUE THREAD

**Issue by roguecreatives** [thenewwazoo/homebridge-lutron-caseta-leap#151]
**Describe The Bug:**
When using the bridge on the Hoobs Pro it does not discover my Lutron Caseta Smart Hub 2. I have tried everything I can think of. The Hoobs Pro and the Smart Hub are connected to the same unmanaged switch coming out of the router. I've tried connecting them both to the router as well with no luck. I've even tried it with another bridge with no luck.

**To Reproduce:**
Add the bridge and try to configure. Click on "Start Custom Plugin UI."

**Expected behavior:**
When clicking "Start Custom Plugin UI" the window for Lutron Device Configuration comes up. At the bottom it should show show my bridge that it has discovered on the network but it does not.

**Logs:**

```
I've attached the logs. The only thing I see in the log that seems related is:

12:57:37 PMLutron Casetaleap Bridgewarnunhandled rejection: SyntaxError: Unexpected token u in JSON at position 0 SyntaxError: Unexpected token u in JSON at position 0 at JSON.parse (<anonymous>) at cloneJson (/usr/src/services/json.ts:36:17) at FSWatcher.<anonymous> (/usr/src/main.ts:151:46) at FSWatcher.emit (node:events:513:28) at FSWatcher.emitWithAll (/usr/lib/hoobsd/node_modules/chokidar/index.js:540:8) at FSWatcher._emit (/usr/lib/hoobsd/node_modules/chokidar/index.js:632:8) at listener (/usr/lib/hoobsd/node_modules/chokidar/lib/nodefs-handler.js:370:20)
```

**Plugin Config:**

```json
Since the plugin won't run or discover my bridge, I have no config files.
```

**Screenshots:**

**Environment:**

* **Plugin Version**: 2.5.3 (I have tried previous versions with no luck)
* **Homebridge Version**:  1.6.1
* **Node.js Version**: 18.16.1
* **NPM Version**:  ?
* **Operating System**:  Hoobs Pro controlled through the Mac app and/or web interface.

**Comment by thenewwazoo** [comment]
Sorry, I don't support Hoobs. I suggest reaching out to them for support.
