### ISSUE TITLE
Pico to trigger brightness?

### ISSUE THREAD

**Issue by MonDonalds** [thenewwazoo/homebridge-lutron-caseta-leap#153]
**Describe Your Problem:**

is there a way to map a pico button to increase or decrease the brightness of a light?

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by thenewwazoo** [comment]
Sorry, no, that’s a limitation of HomeKit. Button actions must be idempotent.
