### ISSUE TITLE
Would you consider adding support for Caseta Switches/Dimmers

### ISSUE THREAD

**Issue by neema2** [thenewwazoo/homebridge-lutron-caseta-leap#159]
Hi!

Amazing work thank you for doing this!

Read in the readme that you specific did not add support for switches and dimmers but wondering if you would reconsider for a few reasons:

1/ native HomeKit support for these does not include double tap and long press!

2/ there is a crazy delay with native integration for switches, if you made them look like picos/general buttons this might actually solve that issue 

3/ would love switches to work exactly like picos but hardwired so I do not have to think about battery life

Would be happy to help or donate time/effort/money/switches to get this done!

Thank you!
Neema

**Comment by thenewwazoo** [comment]
Unfortunately, the last time I checked (though I doubt this has changed), wall devices don't expose buttons - all you get is notification that the dimmer or on/off value has changed, so adding this support isn't possible.
