### ISSUE TITLE
Could not connect to discovered hub

### ISSUE THREAD

**Issue by khowell20454** [thenewwazoo/homebridge-lutron-caseta-leap#19]
**Describe The Bug:**
When restarting home bridge, getting a connection error upon installation of plugin.

**To Reproduce:**
When restarting home bridge.

**Expected behavior:**
Should be showing pico remotes in homebridge/homekit

**Logs:**

See attached.

**Plugin Config:**

{
            "name": "Lutron",
            "secrets": [
                {
                    "bridgeid": "01E71***",
                    "ca": "MII**",
                    "key": "MII**",
                    "cert": "MII**"
                }
            ],
            "platform": "LutronCasetaLeap"
        }

**Screenshots:**

**Environment:**

* **Plugin Version**: 2.2.1
* **Homebridge Version**: 1.4.0
* **Node.js Version**: 16.13.2
* **NPM Version**: 8.3.1
* **Operating System**: Raspbian GNU/Linux Bullseye (11)
[homebridge.log.txt](https://github.com/thenewwazoo/homebridge-lutron-caseta-leap/files/7967180/homebridge.log.txt)

**Comment by thenewwazoo** [comment]
From your log:
```
[30/01/2022, 17:03:43] [Lutron] Could not connect to discovered hub: Error: error:0909006C:PEM routines:get_name:no start line
```

Please review your config.
