### ISSUE TITLE
Pico Remote Resets In HomeKit After Power Outage

### ISSUE THREAD

**Issue by LoganVessell** [thenewwazoo/homebridge-lutron-caseta-leap#22]
### **Environment**
**M1 Mac mini** - macOS Monterey 12.2
**Homebridge** - v1.4.0
**Node.js** - v16.13.1
**NPM** - v8.1.2
**Lutron Caséta LEAP** - v2.2.1

### **Summary**
Following the power outage from the winter storm, my Pico Remote reset itself in HomeKit, removing all settings.

### **How to Reproduce**
1. Make sure your devices are set up properly to HomeKit, at least a Pico Remote is needed.
2. Try unplugging & plugging back in a device, and see how that changes in HomeKit or Homebridge. If not, try two devices at once, and all three if that doesn't work either. (Homebridge, Lutron Hub, Pico Remote.)

### **Expected Results**
The Pico Remote(s) should stay connected and keep it's data, regardless of offline status due to power, unless the plugin is removed from Homebridge.

### **Notes**
I do not have any logs at the time this occurred, unfortunately. But if there's anything I can do to retest this, I'd be happy to help.

**Comment by donavanbecker** [comment]
I have had the same issue. Only once though

**Comment by thenewwazoo** [comment]
Hmm. I bet I know what happened. I added a feature to make Pico remotes disappear when they're removed from the hub, but I see now that [it's not fine-grained enough](https://github.com/thenewwazoo/homebridge-lutron-caseta-leap/blob/master/src/PicoRemote.ts#L177). That should inspect the failed response and only remove the device if it's gotten a 404. As it is, if the bridge times out, the device will be removed. Sorry about that. :(

**Comment by donavanbecker** [comment]
@thenewwazoo No worries.
