### ISSUE TITLE
Lutron 4 Button Pico

### ISSUE THREAD

**Issue by thewolfanator** [thenewwazoo/homebridge-lutron-caseta-leap#26]
Hi, happy to help with getting the 4 button picos working!  I have never done anything like this before so you will have to walk me through the steps starting with Debug Logging - no idea how to do that?

**Comment by thewolfanator** [comment]
ok.

**Comment by thenewwazoo** [comment]
If you still have the files from when you set up the bridge for the first time (the python script), I think the easiest way is to send me the output from the following script:
```python
#!/usr/bin/env python3

import asyncio
import logging

logging.basicConfig(level=logging.DEBUG)

from pylutron_caseta.smartbridge import Smartbridge

async def get_buttons():
    # `Smartbridge` provides an API for interacting with the Caséta bridge.
    bridge = Smartbridge.create_tls(
        "192.168.1.151", "caseta.key", "caseta.crt", "caseta-bridge.crt"
    )
    await bridge.connect()

    await bridge._request("ReadRequest", "/button")

loop = asyncio.get_event_loop()
loop.run_until_complete(get_buttons())
```

Edit that script to set the IP address correctly, and run from the same directory that has the key, cert, and ca files in it. So, something like:

```bash
. env/bin/activate
python3 buttons.py
```

**Comment by thewolfanator** [comment]
Hey bud.  Sorry completely got swamped with work and didn’t get back to this.  Going to do this today!!

**Comment by thewolfanator** [comment]
Hey, sorry, got crazy busy with work....  I finally just sat down to do this, but I am not sure where to start?  The only experience I have with Python was to get your plugin working.  You will have to give me all the steps of what I type in to terminal on my mac - need the "complete idiot" version.  I have some time today to tinker, so let me know.

**Comment by thenewwazoo** [comment]
Sorry I’m actually out most of the day so I may not be able to help semisynchronously. Basically it requires following the old setup instructions that involved Python, and running this script instead of the one that gets the certificates. I’ve been thinking of ways to add unknown-device discovery directly in the plug-in, so if you don’t get to it, that’s okay (but might take longer)

**Comment by thewolfanator** [comment]
Are we still going to try this?

**Comment by thenewwazoo** [comment]
I'd still love to get this feature added, yes!

Start with [these instructions](https://github.com/thenewwazoo/homebridge-lutron-caseta-leap#legacy-configuration). Do the "Get your bridge credentials" section, and then run the above script in that same terminal right after.

**Comment by wsmeyer90277** [comment]
> I'd still love to get this feature added, yes!
> 
> Start with [these instructions](https://github.com/thenewwazoo/homebridge-lutron-caseta-leap#legacy-configuration). Do the "Get your bridge credentials" section, and then run the above script in that same terminal right after.

Are you still waiting on the output of that script?

**Comment by thewolfanator** [comment]
Yes, I just wasn’t sure what to do?

**Comment by wsmeyer90277** [comment]
> I'd still love to get this feature added, yes!
> 
> Start with [these instructions](https://github.com/thenewwazoo/homebridge-lutron-caseta-leap#legacy-configuration). Do the "Get your bridge credentials" section, and then run the above script in that same terminal right after.

I'm willing to help but not sure where you are at with this

**Comment by thenewwazoo** [comment]
Sorry, still just waiting for someone to run the script and provide the output. :)

**Comment by wsmeyer90277** [comment]
> Sorry, still just waiting for someone to run the script and provide the output. :)

I'll do it first thing in the morning :)

**Comment by wsmeyer90277** [comment]
> Sorry, still just waiting for someone to run the script and provide the output. :)

I can't even get started as I can't find where to download the get_lutron_cert.py file

**Comment by thenewwazoo** [comment]
I’m thinking it’s going to be easier if I could get my hands on one myself. If anyone felt like donating one, that would be ideal, and would get this done :)

**Comment by wsmeyer90277** [comment]
> I’m thinking it’s going to be easier if I could get my hands on one myself. If anyone felt like donating one, that would be ideal, and would get this done :)

That was one of the first things I thought of but they've been on backorder from Lutron since the pandemic. They're only available now from hoarders that want a ridiculous amount for them 🤬

The other way I thought of is to give you my ip address and port forward to my hub so you can run scripts on it remotely.

**Comment by thewolfanator** [comment]
Where are you located?

**Comment by wsmeyer90277** [comment]
Los Angeles

**Comment by thenewwazoo** [comment]
I'm in the SFBA. Another gracious user sponsored occupancy sensor support by sending me an amazon gift card that I used to order a test unit, so something like that is an option.

**Comment by basemodel72** [comment]
Hey! I too am interested in getting 4 button support. Id be happy to order a remote and have it shipped to you

**Comment by thenewwazoo** [comment]
That’d be great! Shoot me an email and we’ll coordinate
