### ISSUE TITLE
Auto Remove Accessory

### ISSUE THREAD

**Issue by simplytoast1** [thenewwazoo/homebridge-lutron-caseta-leap#30]
**Is your feature request related to a problem? Please describe:**
No Problem

**Describe the solution you'd like:**
I would love that when an accessory is removed from the Lutron Hub (via the app) the device is also removed from HomeKit without the need to manually remove the cached accessory.

**Describe alternatives you've considered:**
This is more inline with other plugin behavior

**Additional context:**
N/A

**Comment by thenewwazoo** [comment]
Thanks for the request! I actually tried implementing this already and screwed it up 😅 With some refactoring it shouldn’t be too hard to do, the programmer would need to distinguish between a communications failure and a valid exception object, and remove (or not insert) the accessory. Right now creating an accessory either defers setup in a synchronous constructor and adds the accessory or throws early. There’s no path at the moment to defer adding the accessory. Hopefully that helps anyone who might feel like picking this up. I doubt I’m going to get to it soon.

**Comment by simplytoast1** [comment]
By no means is this an "urgent" or even "important" feature.  Its rather trivial to remove a cached accessory this is more of a pie in the sky wishlist item.  My other enhancement is more of an ask than this is.  I will close this enhancement to clear the queue.

**Comment by thenewwazoo** [comment]
Gonna re-open this since it's still a valid request, and anyone who wants to contribute can pick this up. :)

**Comment by thenewwazoo** [comment]
My [most recent commit](https://github.com/thenewwazoo/homebridge-lutron-caseta-leap/commit/01d88a09b73f0268ce22c9ecf29abc1c8173c4a4) reduces this feature request to the problem of cache invalidation. To wit, how do we know that an accessory has truly been removed, and not that we simply have not discovered it _yet_?

**Comment by thenewwazoo** [comment]
I'm going to close this as, effectively, won't-fix. Removing devices is very likely to be an exceptionally rare operation, and there's an established path for removing cached accessories that does the job, even if it's a bit ugly.
