### ISSUE TITLE
Just Works setup not just working - can't find Bridge

### ISSUE THREAD

**Issue by mLowryP** [thenewwazoo/homebridge-lutron-caseta-leap#32]
**Describe Your Problem:**
Plugin installs, but sits and spins at the "spinning gear" screen when trying to configure.  Logs show it is doing /search but never finds anything.  get_lutron_cert.py works fine, and Bridge works otherwise.  Tried to add secrets to JSON manually but no such luck.

**Logs:**

[09/03/2022, 19:02:46] [Homebridge UI] [homebridge-lutron-caseta-leap] Incoming Request: /search
[09/03/2022, 19:02:51] [Homebridge UI] [homebridge-lutron-caseta-leap] Terminating child process...
[09/03/2022, 19:02:51] [Homebridge UI] [homebridge-lutron-caseta-leap] Child process ended
[09/03/2022, 19:04:07] [Homebridge UI] Changes to config.json saved.

**Plugin Config:**

{
    "bridge": {
        "name": "Homebridge123456",
        "username": "removed",
        "port": 51585,
        "pin": "removed"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "August Locks",
            "email": "removed",
            "password": "removed",
            "code": "removed",
            "installId": "removed",
            "platform": "AugustLocks"
        },
        {
            "name": "TplinkSmarthome",
            "addCustomCharacteristics": true,
            "deviceTypes": [
                "plug",
                "bulb"
            ],
            "platform": "TplinkSmarthome"
        },
        {
            "name": "Lifx Plugin",
            "duration": 0,
            "brightnessDuration": 300,
            "colorDuration": 300,
            "default": "0.0.0.0",
            "broadcast": "255.255.255.255",
            "lightOfflineTolerance": 3,
            "messageHandlerTimeout": 45000,
            "resendPacketDelay": 150,
            "resendMaxTimes": 3,
            "updates": true,
            "debug": false,
            "autoDiscover": true,
            "platform": "LifxPlugin"
        },
        {
            "platform": "LutronCasetaLeap",
            "name": "LutronCasetaLeap",
            "secrets": [
                {
                    "bridgeid": "removed",
                    "ca": "-----BEGIN CERTIFICATE-----removed-----END CERTIFICATE-----",
                    "key": "-----BEGIN PRIVATE KEY-----removed-----END PRIVATE KEY-----",
                    "cert": "-----BEGIN CERTIFICATE-----removed-----END CERTIFICATE-----"
                }
            ]
        }
    ]
}

**Screenshots:**

<img width="782" alt="image" src="https://user-images.githubusercontent.com/101300741/157567206-61b560e5-0d8a-4d1c-b408-5d56d5566eef.png">

**Environment:**

* **Plugin Version**: 2.3.0
* **Homebridge Version**: 1.4.0
* **Node.js Version**: 16.14.0
* **NPM Version**: 8.5.1
* **Operating System**: hb-service

**Comment by mLowryP** [comment]
Nevermind.  The issue was entirely with CenturyLink's router.  Thanks for writing a lovely plugin.

**Comment by thenewwazoo** [comment]
🤣 thank you and I’m glad you got it sorted. For future reference, what was the problem?

**Comment by hmangnx** [comment]
Any reference on why this was happening? I am having this problem. If I get it to detect it will work for a bit and then stop. Then I try to pair the hub again and it won't find it and just spins.
