### ISSUE TITLE
Pico 4-Button Scene Controller

### ISSUE THREAD

**Issue by mmfromut** [thenewwazoo/homebridge-lutron-caseta-leap#33]
**Is your feature request related to a problem? Please describe:**

**Describe the solution you'd like:**

Are you able to add the 4-button scene controller PICO - this would be huge!  PJ2-4B-GWH-XXX remotes
**Describe alternatives you've considered:**

**Additional context:**

**Comment by thenewwazoo** [comment]
This looks like a dupe of #26. If you could grab the output of the script there, I can add support pretty quickly.
