### ISSUE TITLE
Installing plugin causes HOOBs bridge to go unresponsive

### ISSUE THREAD

**Issue by gray8211** [thenewwazoo/homebridge-lutron-caseta-leap#37]
Installing plugin causes HOOBs bridge to go unresponsive. Uninstalling plugin causes the bridge to begin responding again. Is this a HOOBs issue? I'm running HOOBs 4.0.110 and Homebridge 1.3.4

**Comment by thenewwazoo** [comment]
No idea! ☺️ I don’t use HOOBS and haven’t tried. If you can enable debug mode and provide log output, I’d love to take a look.

**Comment by garlandcox** [comment]
It appears to be HOOBs, I have an instance of homebridge running on my synology NAS and no issues at all.

**Comment by afarkler** [comment]
I have the same issue on Hoobs 4.0.104 + Homebridge 1.3.4.  Installing on its own bridge.  Other bridges remain responsive.

**Comment by gray8211** [comment]
@afarkler were you able to get the new bridge to start up? When I created a bridge for Caseta LEAP it wouldn't stay online

**Comment by afarkler** [comment]
@gray8211   No.  I tried installing/uninstalling/reinstalling several times.  I could never get to the Activate button and the one bridge always stopped running.

**Comment by thenewwazoo** [comment]
It's probably worth filing a ticket over with the [HOOBS project itself](https://github.com/hoobs-org/HOOBS/issues)

**Comment by ryanmcwh** [comment]
Having the same issue here with Hoobs. Tried to get into the weeds downloading Python but the next steps were above my knowledge level. I see the 4 fields for the device credentials, just cant get them. Will wait a few weeks to see if Hoobs does anything, otherwise I'll go pure HomeBridge on a Raspberry Pi.

**Comment by ftoralesacosta** [comment]
This might be fixed on HOOBS side

https://github.com/hoobs-org/HOOBS/issues/1805

I was having trouble over the weekend. I re-installed the plugin and the gui, as well as unresponsiveness were fixed for me.

**Comment by cptgreedle** [comment]
Still haven't figured it out myself. Having the same problem. Every time I try to start up the hub, it crashes.
This is the error I get with debug mode on:

```
1:46:52 PMLutron Caseta Leap BridgeBridge change
1:46:52 PMlutroncasetaleapbridge stopping
1:46:53 PMHomebridgeWARNINGunhandled rejection: SyntaxError: Unexpected token u in JSON at position 0
1:46:55 PMLutron Caseta Leap Bridge starting
1:46:57 PMlutroncasetaleapbridge stopping
1:47:00 PMLutron Caseta Leap Bridge starting
1:47:05 PMLutron Caseta Leap BridgeLoaded plugin 'homebridge-lutron-caseta-leap'
1:47:05 PMLutron Caseta Leap BridgeLoading 1 platforms...
1:47:05 PMLutron Caseta Leap BridgeLutronCasetaLeapLutronCasetaLeap starting up...
1:47:05 PMLutron Caseta Leap BridgeWARNINGunhandled rejection: TypeError: config.secrets is not iterable
```

**Comment by thenewwazoo** [comment]
This is closed on the HOOBS side, so if someone would be so kind as to submit a PR to the readme confirming compatibility, that would be much appreciated. Closing this up.

**Comment by ryanmcwh** [comment]
Confirmed working on Hoobs for me, thanks for the help!
