### ISSUE TITLE
UI not detecting hb

### ISSUE THREAD

**Issue by balboafer** [thenewwazoo/homebridge-lutron-caseta-leap#39]
Hi! 
I'm writing you regarding the installation of the Leap Plug in because the UI is not detecting mine and i don't have the skills to configure it via legacy method, can you help me with this?
Kind regards.

```
6/4/2022 17:59:12Lutron Caseta Leap BridgeLutronCasetaLeapLutronCasetaLeap starting up...
6/4/2022 18:30:43Lutron Caseta Leap BridgeLutronCasetaLeapLutronCasetaLeap starting up...

```

**Plugin Config:**

```json
{
    "platform": "LutronCasetaLeap"
}
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 4.0.104
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by thenewwazoo** [comment]
I took your question as an opportunity to finally add a troubleshooting section to the README. Unfortunately, I don't have any way to know why your network isn't passing broadcast packets around.

**Comment by balboafer** [comment]
Hi Brandon and thank you for your fast response!
What can I do to help you?

Fernando Balboa d'Argence.

El 7 abr 2022, a la(s) 0:44, Brandon Matthews ***@***.***> escribió:

﻿

I took your question as an opportunity to finally add a troubleshooting section to the README. Unfortunately, I don't have any way to know why your network isn't passing broadcast packets around.
