### ISSUE TITLE
Skipping unimplemented device

### ISSUE THREAD

**Issue by ucfhall** [thenewwazoo/homebridge-lutron-caseta-leap#4]
My setup is a Smart Bridge (L-BDG2-WH), three in-wall dimmer switches (P-PKG1W-WH) and one lamp dimming smart plug (P-PKG1P-WH). None of them are appearing in Homebridge. I ran the get_lutron_cert.py script to get the caseta-bridge.crt,  caseta.key and caseta.crt files, inserted the text into the appropriate fields in the plugin config...this is what I get in the log:

[2/18/2021, 6:53:58 PM] [LutronCasetaLeap] Got unimplemented device type SmartBridge , skipping
[2/18/2021, 6:53:58 PM] [LutronCasetaLeap] Got unimplemented device type WallDimmer , skipping
[2/18/2021, 6:53:58 PM] [LutronCasetaLeap] Got unimplemented device type PlugInDimmer , skipping
[2/18/2021, 6:53:58 PM] [LutronCasetaLeap] Got unimplemented device type WallDimmer , skipping
[2/18/2021, 6:53:58 PM] [LutronCasetaLeap] Got unimplemented device type WallDimmer , skipping

So clearly the encryption values are correct because HB is communicating with the bridge, hence why it sees the list of devices attached.

**Comment by thenewwazoo** [comment]
Yep! As I said in the README, the only thing that this plugin adds is support for SerenaTiltOnlyWoodBlind devices, since the hub supports other types of devices natively.

I am _absolutely_ interested in supporting other devices, if you'd like to contribute. There's a (very) brief overview of what's needed at the bottom of the README.

**Comment by ucfhall** [comment]
Ah my bad...I missed that part of the README. I could probably assist with the dimmers; the Tuya plug-in uses similar code structure. 

On Feb 19, 2021, at 11:41, Brandon Matthews <notifications@github.com> wrote:

﻿
Yep! As I said in the README, the only thing that this plugin adds is support for SerenaTiltOnlyWoodBlind devices, since the hub supports other types of devices natively.

I am absolutely interested in supporting other devices, if you'd like to contribute. There's a (very) brief overview of what's needed at the bottom of the README.
