### ISSUE TITLE
Add support to publish events via MQTT

### ISSUE THREAD

**Issue by mhuca** [thenewwazoo/homebridge-lutron-caseta-leap#43]
**Is your feature request related to a problem? Please describe:**
Currently Pico remotes can only trigger single button press based actions in HomeKit automations. I'm looking to be able to control non-lutron lights/devices in particular dimming of lights.

**Describe the solution you'd like:**
Simularly to the Homebridge myQ pluggin where there is an optional MQTT settings which contains the MQTT Broker URL and MQTT Base topic where on an event JSON object is published whenever a Lutron event occurs. E.G. Pico Button pressed.

**Describe alternatives you've considered:**
I've tried installing Home Assistant to be able to create automations to when events occur but installing a new server just to control a few lights is overkill.

**Additional context:**

**Comment by thenewwazoo** [comment]
This is definitely outside the scope of the plug-in’s function, but I think you might be interested in [this repository](https://github.com/terafin/mqtt-lutron-leap-bridge), created by a contributor to the underlying library that both use.

**Comment by mhuca** [comment]
Thanks.. I'll take a look... but I'm not very advanced in this stuff...
