### ISSUE TITLE
Pushing Your Buttons!

### ISSUE THREAD

**Issue by MoTechnicalities** [thenewwazoo/homebridge-lutron-caseta-leap#44]
With this new ability to push our Pico buttons into the HomeKit scene, I thought it would be great to post some HomeKit Button Shortcuts to help you push your button's abilities to the limit. 👉🔘

**Comment by MoTechnicalities** [comment]
**Advanced Button Toggle**

👉🔘 SINGLE PRESS
—— SHORTCUT ACTION ——
If Light is 45
   SET light to 100
   Stop shortcut
End If
If Light is OFF
   SET light to 100
   Stop shortcut
End If
Set light to OFF

**What this does.**
I use advanced automations with a light. I have sensor that will turn a light on to 45% brightness only at night if motion is detected and a shortcut that will turn it back off 20 seconds after motion stops and the bulb is 45%. With this button shortcut, I can use my Pico to toggle the light out of motion detect mode by setting it to 100% brightness. And with the same button turn it off, which returns it back to sensor control.

**Comment by MoTechnicalities** [comment]
**ON, DIM, DIMMER, DIMMEST**

👉🔘 BUTTON PRESS
—— SHORTCUT ACTION ——
If light is 100%
   Set light to 75%
   Stop Shortcut
End If
If light is 75%
   Set light to 50%
   Stop Shortcut
End If
If light is 50%
   Set Light to 25%
   Stop Shortcut
End If
If light is 25%
   Set Light to 100%
   Stop Shortcut
End If
Set Light to 100%

**Comment by thenewwazoo** [comment]
I appreciate the effort, but I don't think a github issue is the right place for this info.
