### ISSUE TITLE
Directions for Occupancy Sensors

### ISSUE THREAD

**Issue by markhurlburt** [thenewwazoo/homebridge-lutron-caseta-leap#46]
I'm running 2.3.6 of the leap plugin and am hoping to be able to expose occupancy sensors in Homekit. I was able to add the sensor through the lutron app and I can see it in the "accessories" tab in Homebridge but it doesn't show up in homekit. Is there another step to setup? Adding directions to the readme to explain the proper process for this would be greatly appreciated!

**Comment by thenewwazoo** [comment]
Looks like you got it sorted. Can you help me understand what changed, so I can update the docs if needed?

**Comment by mjreddy** [comment]
@markhurlburt - any chance you remember how you fixed this? I also just installed this HB plugin and have the occ sensor showing up in HB's accessories but I can't find it (or pico remotes for that matter) in HomeKit. Thanks!

**Comment by mjreddy** [comment]
@thenewwazoo - I saw another post #92 that mentioned activating the plugin as a child bridge. I tried that it got my occupancy sensor to show up. Thanks for making this plugin!

**Comment by thenewwazoo** [comment]
Sounds like I should document that as a requirement for setup, thank you!

**Comment by thenewwazoo** [comment]
Weirdly, I just checked and I don't run my own setup in a child bridge. I'll still add it as a possible troubleshooting step, though, since it seems to help somehow! I really hate mysteries. 😆
