### ISSUE TITLE
Hoobs - Connect smart bridge not working?

### ISSUE THREAD

**Issue by BarnesGH** [thenewwazoo/homebridge-lutron-caseta-leap#48]
When I click “Connect smart bridge” a text box comes up saying “please wait for the bridge to start” but nothing happens. Am I missing something?

**Comment by thenewwazoo** [comment]
Unfortunately, I don't use HOOBS and can't really provide support for it. If you figure out what's wrong, please respond to this thread w/ info, or submit a PR with an update to the README. :)
