### ISSUE TITLE
Pico switches not showing in HomeKit

### ISSUE THREAD

**Issue by freshlydoug** [thenewwazoo/homebridge-lutron-caseta-leap#54]
Hi, I’ve had my RA2 select and pico remotes working well via homebridge and HomeKit.  I added a “keypad” and a second “scenes” switch and neither would show in HomeKit, despite appearing in homebridge.  I have tried to remove the switches and disable / enable the plugin and now I’m in a situation where none of the 6 pico switches are showing in HomeKit, despite all being listed in homebridge.  Any help much appreciated.  Thank you.

**Comment by freshlydoug** [comment]
I should add that clearing the accessories cache didn’t seem to make any difference.  I fixed this by setting up a new homebridge just for this plugin.  Again all on the latest releases but after adding the new homebridge (two homebridges one homekit) all switches came over into HomeKit.

**Comment by thenewwazoo** [comment]
Well, that's super duper weird. I wish I knew what happened, but I'm glad it's working for you! I don't have an RA2 to test with, so reports that it works make me super happy. :)

**Comment by freshlydoug** [comment]
I’m super happy the RA2 works too :). Long may it continue, I was panicking for a bit there.
