### ISSUE TITLE
Plugin unable to connect to RA3 Processor after initial setup

### ISSUE THREAD

**Issue by mservidio** [thenewwazoo/homebridge-lutron-caseta-leap#55]
Based on lutron-leap-js and the Homebridge settings UI it appears that this has support for RadioRA3 processors. I was able to successfully connect the RadioRA3 processor through the settings on Homebridge UI and set it up by pushing the button on the RadioRA3 processor. However, after restarting HomeBridge, the status logs show an error on a request to the processor:

```
[7/22/2022, 12:54:37 PM] [Lutron] Failed to process devices on new bridge 0421xxx3: TypeError: Cannot read properties of undefined (reading 'Devices')
```

I also have a Caseta bridge set up with the plugin which connects and is working great.

**Comment by thenewwazoo** [comment]
Yeah, unfortunately the RA3 device model is totally different to the Caséta model, and I don't have one on-hand to use for development. @johninaustin [did some work](https://github.com/gurumitts/pylutron-caseta/issues/80#issuecomment-1032229694) to this end that might be of use to you if you want to pursue it further.
