### ISSUE TITLE
Plugin is stuck on Incoming Request: /search, bridge is never found

### ISSUE THREAD

**Issue by braddunlap** [thenewwazoo/homebridge-lutron-caseta-leap#56]
Title explains the issue I am having: Plugin is stuck on Incoming Request: /search, bridge is never found. I realize this is probably some kind of network issue and it is difficult to debug, but I am really scratching my head trying to figure it out. If anyone has any pointers of where I might look, I would greatly appreciate it.

I have looked at all my Bonjour settings in both HomeBridge and the Synology and everything looks fine.

I see Lutron bridge on the network and it is broadcasting over Bonjour.
I see Homebridge as a Bonjour host on my network

Synology NAS and Lutron Bridge are plugged into the same switch.

Log:
[7/22/2022, 1:23:58 PM] [Homebridge UI] [homebridge-lutron-caseta-leap] Incoming Request: /search
[7/22/2022, 1:28:22 PM] [Homebridge UI] [homebridge-lutron-caseta-leap] Terminating child process...
[7/22/2022, 1:28:22 PM] [Homebridge UI] [homebridge-lutron-caseta-leap] Child process ended

Environment:
Eero Pro 6 router (I am suspect of this, but I don't know what setting would cause it to not be discovered)
Synology NAS DSM v7.1
HomeBridge v1.5.0 mDNS Advertiser: Ciao, also tried Bonjour HAP
homebridge-lutron-caseta-leap plugin version: v2.3.9

**Comment by thenewwazoo** [comment]
I made a change to how mDNS discovery works that might help with this, please give v2.4.0-beta0 a try. If it _doesn't_ work, unfortunately, I've got no ideas.
