### ISSUE TITLE
Picos Partially Respond 

### ISSUE THREAD

**Issue by simplytoast1** [thenewwazoo/homebridge-lutron-caseta-leap#62]
**Describe The Bug:**
A few days ago I noticed that some of my Picos are not reporting button presses to Homebridge.  Initially I thought it was an issue with the range extender but native Lutron actions were being performed on the button presses.  I’ve rebooted the hub, plugin, extenders several times and no luck.  In the logs the pico is discovered and setup.

**To Reproduce:**
Press a button on a Pico remote and check logs to see if the action is reported.

**Expected behavior:**
Button press to be logged

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**: 2.4.0
* **Homebridge Version**:  1.5.0 
* **Node.js Version**: 16.15.1
* **NPM Version**:  8.11
* **Operating System**: macOS

**Comment by simplytoast1** [comment]
I think that it has SOMETHING to do with caching.  I took a known working Pico remote all around the house and it was responsive and then a remote that stopped working and put it next to the hub and still nothing.

**Comment by simplytoast1** [comment]
It seems a Node upgrade actually fixed the issues.  Closing.

**Comment by thenewwazoo** [comment]
Weird! From what version to what version?

**Comment by simplytoast1** [comment]
16.14 to 16.16

it was super weird.  I rebooted the HB server, all Lutron hubs and extenders.  Some picos never responded.  They did show statuses in the detailed logging.  I said what they heck and updated Node and after that, boom.

Same reaction here.  Very weird.

I still have the detailed logs I plan on reviewing tomorrow.
