### ISSUE TITLE
Can a second instance be run in a child bridge?

### ISSUE THREAD

**Issue by JoelGit** [thenewwazoo/homebridge-lutron-caseta-leap#63]
**Describe Your Problem:**

I am using two Caseta hubs. Can a second instance of the plugin be run, perhaps via a child bridge, to be able to use the plugin with both hubs?

**Comment by thenewwazoo** [comment]
Hi @JoelGit! I've done some poking around and had [some discussions about mDNS](https://github.com/thenewwazoo/lutron-leap-js/issues/22) related to multiple bridges. I _expected_ it to work, but only have one and obviously hadn't tested it. I'd love to get it working. Can you describe what you see when you try?

**Comment by JoelGit** [comment]
Will do!

**Comment by thenewwazoo** [comment]
Any chance you have tested this? I still expect it to Just Work.

**Comment by thenewwazoo** [comment]
Please reopen if this is still a problem
