### ISSUE TITLE
btrk invalid action for state. resetting (in red from log)

### ISSUE THREAD

**Issue by smkdog420** [thenewwazoo/homebridge-lutron-caseta-leap#64]
**Describe The Bug:**
Sometimes a pico won't work properly.  Will see "btrk invalid action for state. resetting"

**To Reproduce:**
Sometimes it will work and other times it won't.  This example is to close/open a garage door.  two of the buttons will work to turn on/off lights.  Thought this might have something to do with it being a garage door, but it works sometimes.  Also seeing similar with some shade/blinds that are not HK native.

**Expected behavior:**

**Logs:**

[12/08/2022, 15:47:52] [Lutron] btrk invalid action for state. resetting
[12/08/2022, 15:47:52] [Lutron] Button /button/119 on Pico remote Office Office Garage got action Release

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by thenewwazoo** [comment]
Hmm. I broke one of my cardinal rules of programming and emitted identical log lines in multiple places! If you could enable debug logging and include some the lines surrounding those two, that will enable me to figure out where the failure is. I'm not sure if a message is getting dropped/lost, if the remote is emitting a message type I don't recognize (or haven't seen before), or if it's a long/double press problem.

**Comment by thenewwazoo** [comment]
And thank you for the report! This is a new feature, and I appreciate you taking the time to report a problem.

**Comment by smkdog420** [comment]
my pleasure, I am thrilled you took the time to create this bad ass solution and responding to me.  Im a total tech idiot, but will try to give you what you are looking for later today.....I did see how to turn on debug for this.  It is not long or double push; I am not using a lot of those as I'm trying to keep it simple for the wife.  I noticed this on one of the 4 button remotes (on/up/down/off - no middle button).  Ive got 1 and 4 controlling the garage lights and 3 & 4 designed to open/close the garage door.  Ive tried same in other rooms with same concept 1&4 on/off lights and 3&4 opening/closing the room's blinds....and have had troubles with it sometime working and getting that same error message in hb....problem is I dont always have the HB log open when Im getting a failure to respond properly.  thanks again for creating this......I am by noooo means complaining cause

**Comment by thenewwazoo** [comment]
@smkdog420 any progress on getting the logs? Version 2.4.2 tweaks the log lines a bit to give a bit more clues for diagnosis, so I recommend updating beforehand.

**Comment by smkdog420** [comment]
Sorry, total stoner move; forgot.  thanks for the reminder.  I have enabled debugging but not sure what lines you want.  I have noticed an improvement since the last update but still having some failures here and there.  Lmk how best to test/caputre what you need and I'll get er done today.  apologies again for my failure to deliver (so far)

**Comment by smkdog420** [comment]
Not seeing the error message anymore; thinking your last update cleared it.  Seems to be working well.  I get a few failures, but I feel its those devices (blinds) than your pico plugin.  I've got the log up and running; will keep an eye on it.  Thank you sir

**Comment by thenewwazoo** [comment]
Glad to hear it hasn't re-appeared. Please feel free to re-open this issue if it happens again.
