### ISSUE TITLE
Lutron Pico Model # (PJ2-3BRL-GXX-X01) support

### ISSUE THREAD

**Issue by ghidalgo93** [thenewwazoo/homebridge-lutron-caseta-leap#66]
**Is your feature request related to a problem? Please describe:**

I got a pack of some pico remotes and nearly all work perfectly with your plugin (amazing thank you!), the only one I've had trouble with is with Model #: PJ2-3BRL-GXX-X01, on firmware 2.4

The top of the accessory menu in HomeKit gives the following message:
```
This accessory has not been certified to work with HomeKit so some features may not be available.
```
I've been looking to see if this model is mentioned in your list of supported devices but it looks like some of the links are dead/old so I'm having trouble pinning down your supported models. The following links are broken:

- [2 Button](https://www.lutron.com/en-US/pages/SupportCenter/support.aspx?modelNumber=PJ2-2B&Section=Documents
- [2-Button with raise/lower](https://www.lutron.com/en-US/pages/SupportCenter/support.aspx?modelNumber=PJ2-2BRL&-Section=Documents)
- [3-Button](https://www.lutron.com/en-US/pages/SupportCenter/support.aspx?modelNumber=PJ2-3B&Section=Documents) (untested)
- [3-Button with raise/lower](https://www.lutron.com/en-US/pages/SupportCenter/support.aspx?modelNumber=PJ2-3BRL&Section=Documents)

**Describe the solution you'd like:**

Support added for this pico remote when and if it's possible. Right now, all my others work so it's not like I can't live without it but it sounded like adding support wasn't too difficult. If I can help test please just let me know and I would be happy to contribute to any of your efforts.

**Describe alternatives you've considered:**

Using other supported pico remotes works just fine.

**Additional context:**

![IMG_2316](https://user-images.githubusercontent.com/25713142/184517399-9c396b1f-7bec-403f-992c-f572192c126c.jpeg)
![IMG_2317](https://user-images.githubusercontent.com/25713142/184517407-4ab5b8b2-d443-4763-afd9-d720b51e50b7.jpeg)
![IMG_2318](https://user-images.githubusercontent.com/25713142/184517409-2578ad83-2263-4888-bd8d-93f065bc71bb.jpeg)

**Comment by smkdog420** [comment]
all my picos and everything that comes into hk via homebridge has "...not certified..." for me.  Ive got these same picos working fine.  Shows up with 5 buttons to configure.

**Comment by thenewwazoo** [comment]
Yeah, that message is part of HomeKit, and caused by the fact that Homebridge accessories use the non-commercial version of the HomeKit Accessory Protocol. Rest assured that everything works as expected (barring bugs, of course!).

**Comment by thenewwazoo** [comment]
Oh, I just re-read your report and missed that you're reporting that your PJ2-3BRL isn't working as expected. I'm going to re-open this issue. Can you describe more about what's not working?

**Comment by JoelGit** [comment]
May I ask,  more generally, what is needed to support a new Pico? I'm looking to use a PJ2-3BRL-GWH-S01, and if it won't work, curious how to make it work. Seems to align with initial submission.

**Comment by thenewwazoo** [comment]
[This code comment](https://github.com/thenewwazoo/homebridge-lutron-caseta-leap/blob/main/src/PicoRemote.ts#L9) is the intro to the map that drives Pico support. Once the button numbers are known and can be mapped to their physical location, a new entry is added, and the device type string is added to [the Pico section](https://github.com/thenewwazoo/homebridge-lutron-caseta-leap/blob/main/src/platform.ts#L234) of the startup code.

**Comment by JoelGit** [comment]
Thanks for that info. Luckily enough that Pico simply worked!

**Comment by thenewwazoo** [comment]
@ghidalgo93, the PJ2-3BRL-XXX-X01 devices are expected to work, so please reopen with more details if you're still having problems.
