### ISSUE TITLE
Problem with responsiveness of pico remotes

### ISSUE THREAD

**Issue by ryanjdesalvo** [thenewwazoo/homebridge-lutron-caseta-leap#67]
> Hi there. Having some responsiveness issues with the pico remotes. Have philips hue and Lutron bridges customized with homekit to trigger a scene with both sets of lights. Sometimes a light doesn’t trigger, staying on prior setting, while the rest update to the correct scene. It is a random light during the instance. I have 3 of these pico remotes, all with a similar problem. Also, it happens pretty often. Maybe 20% of button presses.

Wondering what the process would be to see if there is anything wrong. What can I give you to help see if there are problems? Thanks!

**Comment by thenewwazoo** [comment]
Unfortunately, I suspect this is a problem with HomeKit. The general path that a button press takes is:
* you press the button on the remote
* the remote tells the Smart Bridge 2 that a button was pressed (or released)
* the Smart Bridge 2 tells Homebridge that a button was pressed (or released)
* Homebridge updates the Stateless Programmable Button's characteristic (which is a complicated way of saying "Homebridge tells HomeKit a button was pressed")
* HomeKit sees the characteristic update and updates other devices' characteristics based on the scene definition (that is, "HomeKit sends messages to the things in the scene")

Up until the last line, it's pretty all-or-nothing. Either a message is received or it's not, for each link in the chain. In the last one, though, the HomeKit hub acts on all the various lights (or other devices) by sending potentially-many messages to whatever devices (or hubs) are involved in the scene. If one of those messages gets lost or ignored, you might see random lights stay on or off. At that point, though, the plugin's work has been completed successfully and it's beyond its control.

If that doesn't match what you're seeing, please let me know. :)

One possible solution is to add code in the plugin to expose Lutron scenes inside HomeKit, sort of like [this feature request](https://github.com/thenewwazoo/homebridge-lutron-caseta-leap/issues/59). I don't currently have plans to implement it, but if you're up for it, I think it'd be great.

**Comment by ryanjdesalvo** [comment]
Gotcha thanks for the update. I figured that may be the case. Improved
interference by distancing router from the bridges 5+ feet, but yeah
problem persists, albeit better (for now). I’m still learning on CS50 lol
so my level of coding competence is, limited… Lol. Maybe one day. Anyways
thanks for the update, hopefully Apple improves things in iOS16.
