### ISSUE TITLE
iOS 16 breaks plugin support in Home App

### ISSUE THREAD

**Issue by robbrechter** [thenewwazoo/homebridge-lutron-caseta-leap#76]
Everything was working great prior to upgrade. Upgraded and all Picos disappeared from Home app. All prior programmed functions still work when I physically press switches. Just a heads up.

**Comment by thenewwazoo** [comment]
Fun! Looks like I should test that. Thanks for the heads up

**Comment by thenewwazoo** [comment]
I just updated my phone to iOS 16 and can’t reproduce. How are the Picos configured? Are double tap or long press disabled in your setup?

**Comment by robbrechter** [comment]
so apparently the issue is that they defaulted to be excluded from the Home
view. I was able to find them and turn that on to show them. So this looks
like mostly user error, but thank you for confirming :)

**Comment by thenewwazoo** [comment]
Glad to hear all is well! Thank you for the report
