### ISSUE TITLE
SerenaRollerShade not recognized

### ISSUE THREAD

**Issue by pulseOXE** [thenewwazoo/homebridge-lutron-caseta-leap#78]
**Describe The Bug:**
Error message when initializing HomeBridge: "Failed to process device: Error: Failed to wire new device Living Room Lower Left: Skipping: Device type SerenaRollerShade not recognized. Please file a ticket and tell me about it"

**To Reproduce:**
Have a Serena Roller Shade as part of the Lutron environment

**Expected behavior:**
No error / support in HB

**Logs:**

"Failed to process device: Error: Failed to wire new device Living Room Lower Left: Skipping: Device type SerenaRollerShade not recognized. Please file a ticket and tell me about it"

**Plugin Config:**

"name": "Lutron",
            "platform": "LutronCasetaLeap",
            "options": {
                "filterPico": false,
                "filterBlinds": true,
                "clickSpeedDouble": "default",
                "clickSpeedLong": "default"

**Screenshots:**

**Environment:**

* **Plugin Version**: 2.4.2
* **Homebridge Version**:  1.5.0
* **Node.js Version**: 16.16.0
* **NPM Version**: 
* **Operating System**: Ubuntu 22.04.1

**Comment by thenewwazoo** [comment]
Ah, it looks like I never made an actual release for #75, which this dupes. My eventual goal is to remove this code to avoid having to enumerate every possible device that this plugin _doesn't_ support, which is potentially unbounded. For now, it's not a problem, and you can just ignore it. Thank you for the report!
