### ISSUE TITLE
Add support for Outdoor Plugin Switch

### ISSUE THREAD

**Issue by rhwood** [thenewwazoo/homebridge-lutron-caseta-leap#84]
**Is your feature request related to a problem? Please describe:**
Add support for a Lutron device.

**Describe the solution you'd like:**
The device to be supported.

**Describe alternatives you've considered:**
None. As far as I am concerned the device is natively supported by the Lutron/Homekit integration, but I would like to not see the error.

**Additional context:**
[06/11/2022, 14:56:07] [Lutron] Failed to process device: Error: Failed to wire new device Exterior String Lights: Skipping: Device type OutdoorPlugInSwitch not recognized. Please file a ticket and tell me about it

**Comment by thenewwazoo** [comment]
I've actually removed the enumeration of unsupported devices in the most recent beta (and fixed the ugly error messages besides). Thank you so much for the PR, though, I really appreciate it. I'm going to close this since it no longer applies.
