### ISSUE TITLE
Second Time All Button Mapping has been lost

### ISSUE THREAD

**Issue by Techsticles** [thenewwazoo/homebridge-lutron-caseta-leap#88]
This is the second time since the plugin was released that all button mapping has been lost. 

This time I noticed that all remotes were missing from HomeKit. When they showed up again, the mapping was gone.

**Comment by thenewwazoo** [comment]
Any chance you were able to retain the logs across restarts?

**Comment by thenewwazoo** [comment]
Also, which version(s) are/were you running?

**Comment by Techsticles** [comment]
Version 2.4.2. Not sure how to check the logs.

**Comment by thenewwazoo** [comment]
Hm. Unfortunately, I don't really have any ideas about why this might be, and without logs (or steps to reproduce), I'm afraid I'm probably not going to be able to figure out how to help you. I'll keep this situation in mind when I'm working on it, though, to see if I come up with anything. I'm sorry this happened.
