### ISSUE TITLE
Any plans to add Switch and Dimmer Support

### ISSUE THREAD

**Issue by MattB1981** [thenewwazoo/homebridge-lutron-caseta-leap#90]
Do you have any timeline to implement this or how much more are you looking for in contributions to begin working on this part? 

I'm trying to control everything in my setup so I can use node red to power the automations for my home and homekit native stuff has to come in through another system from what I understand, like HA, openhab or homebridge.

**Comment by thenewwazoo** [comment]
Hi @MattB1981, I don't currently have any plans to add switch or dimmer support to this library, but I actually don't think it's what you want anyway. Or, at least, not directly. This plugin lets HomeKit GUI apps speak to a handful of Lutron devices that aren't already supported. The built-in functionality already permits HomtKit GUI apps to speak to switches and dimmers.

If you want to control Lutron devices programmatically, you'll need to build your own device abstractions on top of the [LEAP protocol library](https://github.com/thenewwazoo/lutron-leap-js) that underpins this plugin.

**Comment by MattB1981** [comment]
Unfortunately for me that's a bit past my abilities. I was hoping to connect all of my devices to homebridge first instead of to homekit since homebridge has an easy integration with Node Red to handle the automations. After this latest iOS update debacle where they fried half my automations I'm moving them out of homekit but I still like the UI. I was hoping for simplicity sake to not have to either move to HA or OpenHab or have a mix of one of those and homebridge.

**Comment by MattB1981** [comment]
(Also fixed the adhd typo's in my first post so it makes more sense now. ack.
