### ISSUE TITLE
Add to readme notes

### ISSUE THREAD

**Issue by bandlaw12** [thenewwazoo/homebridge-lutron-caseta-leap#92]
**Describe Your Problem:**
I was having issues getting my picos to show once I got Homebridge up and running on my synology NAS. It was showing up fine in HB, but nothing in Homekit. I stumbled upon https://www.reddit.com/r/homebridge/comments/yisrnr/pico_remote_not_showing_up_in_homekit/ and realized I needed to go to the plugins page, then click on the wrench, then start the child bridge. Once I did that, everything showed up in Homekit. BUT there was nothing in the documentation to note that or what the Child Bridge function was for. If this could be easily added, it would hopefully save folks time in the future. 

Thank you for developing this plugin!

**Logs:**

**Plugin Config:**

**Screenshots:**

**Environment:**

* **Plugin Version**: 2.4.3
* **Homebridge Version**: v4.50.2 
* **Node.js Version**: 18.21.1
* **NPM Version**: 
* **Operating System**: Docker

**Comment by thenewwazoo** [comment]
Interesting! I don't remember having to do that, and it should Just Work. I'm not sure why it didn't. I'll add a note to the troubleshooting section, probably. Thank you for the report!

**Comment by thenewwazoo** [comment]
I added an admittedly low-quality note to the readme with a pointer to a (much more useful) comment by MoTechnicalities. Hopefully it'll suffice for now. I'll try to improve it in the future, but will close this request for now. Thank you for spurring me to do it!
